-- MySQL Script generated by MySQL Workbench
-- Tue May 17 02:31:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb`;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleName`),
  UNIQUE INDEX `RoleName_UNIQUE` (`RoleName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `IDUser` INT NOT NULL,
  `FIO` VARCHAR(100) NOT NULL,
  `RoleName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `EmailAddress` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NULL,
  `Address` VARCHAR(100) NULL,
  PRIMARY KEY (`IDUser`),
  UNIQUE INDEX `IDUser_UNIQUE` (`IDUser` ASC) VISIBLE,
  INDEX `fk_User_Role1_idx` (`RoleName` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`RoleName`)
    REFERENCES `mydb`.`Role` (`RoleName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `CountryName` VARCHAR(30) NOT NULL,
  UNIQUE INDEX `CountryName_UNIQUE` (`CountryName` ASC) VISIBLE,
  PRIMARY KEY (`CountryName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Manufacturer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Manufacturer` (
  `ManufacturerName` VARCHAR(45) NOT NULL,
  `CountryName` VARCHAR(30) NOT NULL,
  UNIQUE INDEX `ManufacturerName_UNIQUE` (`ManufacturerName` ASC) VISIBLE,
  PRIMARY KEY (`ManufacturerName`),
  INDEX `fk_Manufacturer_Country1_idx` (`CountryName` ASC) VISIBLE,
  CONSTRAINT `fk_Manufacturer_Country1`
    FOREIGN KEY (`CountryName`)
    REFERENCES `mydb`.`Country` (`CountryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Unit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Unit` (
  `UnitName` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `UnitName_UNIQUE` (`UnitName` ASC) VISIBLE,
  PRIMARY KEY (`UnitName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Node` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Node` (
  `IDNode` INT NOT NULL,
  `NodeName` VARCHAR(45) NOT NULL,
  `UnitName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDNode`),
  UNIQUE INDEX `IDNode_UNIQUE` (`IDNode` ASC) VISIBLE,
  INDEX `fk_Node_Unit1_idx` (`UnitName` ASC) VISIBLE,
  CONSTRAINT `fk_Node_Unit1`
    FOREIGN KEY (`UnitName`)
    REFERENCES `mydb`.`Unit` (`UnitName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Part` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Part` (
  `IDPart` INT NOT NULL COMMENT 'номер детали',
  `PartNumber` VARCHAR(45) NULL,
  `PartName` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `ManufacturerName` VARCHAR(45) NOT NULL,
  `IDNode` INT NOT NULL,
  PRIMARY KEY (`IDPart`),
  UNIQUE INDEX `IDPart_UNIQUE` (`IDPart` ASC) VISIBLE,
  INDEX `fk_Part_Manufacturer1_idx` (`ManufacturerName` ASC) VISIBLE,
  INDEX `fk_Part_Node1_idx` (`IDNode` ASC) VISIBLE,
  CONSTRAINT `fk_Part_Manufacturer1`
    FOREIGN KEY (`ManufacturerName`)
    REFERENCES `mydb`.`Manufacturer` (`ManufacturerName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Part_Node1`
    FOREIGN KEY (`IDNode`)
    REFERENCES `mydb`.`Node` (`IDNode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Engine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Engine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Engine` (
  `IDEngine` VARCHAR(10) NOT NULL COMMENT 'название двигателя',
  `Capacity` DOUBLE NOT NULL COMMENT 'объем',
  `HP` INT NOT NULL COMMENT 'мощность',
  `FuelType` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IDEngine`),
  UNIQUE INDEX `IDEngine_UNIQUE` (`IDEngine` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `BrandName` VARCHAR(50) NOT NULL,
  `Country_CountryName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`BrandName`),
  UNIQUE INDEX `BrandName_UNIQUE` (`BrandName` ASC) VISIBLE,
  INDEX `fk_Brand_Country1_idx` (`Country_CountryName` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Country1`
    FOREIGN KEY (`Country_CountryName`)
    REFERENCES `mydb`.`Country` (`CountryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Model` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `BrandName` VARCHAR(50) NOT NULL,
  `ModelName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`BrandName`, `ModelName`),
  INDEX `fk_Model_Brand1_idx` (`BrandName` ASC) VISIBLE,
  UNIQUE INDEX `ModelName_UNIQUE` (`ModelName` ASC) VISIBLE,
  CONSTRAINT `fk_Model_Brand1`
    FOREIGN KEY (`BrandName`)
    REFERENCES `mydb`.`Brand` (`BrandName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Car` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Car` (
  `IDCar` VARCHAR(20) NOT NULL COMMENT 'номер кузова или вин',
  `BrandName` VARCHAR(50) NOT NULL,
  `ModelName` VARCHAR(50) NOT NULL,
  `IDEngine` VARCHAR(10) NOT NULL,
  `ReleaseDate` INT NOT NULL COMMENT 'дата релиза',
  `TransmissionType` VARCHAR(20) NOT NULL,
  `DriveType` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`IDCar`),
  INDEX `fk_CarData_Engine1_idx` (`IDEngine` ASC) VISIBLE,
  UNIQUE INDEX `IDCar_UNIQUE` (`IDCar` ASC) VISIBLE,
  INDEX `fk_Car_Model1_idx` (`ModelName` ASC, `BrandName` ASC) VISIBLE,
  CONSTRAINT `fk_CarData_Engine1`
    FOREIGN KEY (`IDEngine`)
    REFERENCES `mydb`.`Engine` (`IDEngine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Car_Model1`
    FOREIGN KEY (`ModelName` , `BrandName`)
    REFERENCES `mydb`.`Model` (`ModelName` , `BrandName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Favourite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Favourite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Favourite` (
  `IDUser` INT NOT NULL,
  `IDPart` INT NOT NULL,
  PRIMARY KEY (`IDUser`, `IDPart`),
  INDEX `fk_Favourite_Part1_idx` (`IDPart` ASC) VISIBLE,
  CONSTRAINT `fk_Favourite_User1`
    FOREIGN KEY (`IDUser`)
    REFERENCES `mydb`.`User` (`IDUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favourite_Part1`
    FOREIGN KEY (`IDPart`)
    REFERENCES `mydb`.`Part` (`IDPart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Car_has_Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Car_has_Part` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Car_has_Part` (
  `IDCar` VARCHAR(20) NOT NULL,
  `IDPart` INT NOT NULL,
  PRIMARY KEY (`IDCar`, `IDPart`),
  INDEX `fk_Car_has_Part_Part1_idx` (`IDPart` ASC) VISIBLE,
  INDEX `fk_Car_has_Part_Car1_idx` (`IDCar` ASC) VISIBLE,
  CONSTRAINT `fk_Car_has_Part_Car1`
    FOREIGN KEY (`IDCar`)
    REFERENCES `mydb`.`Car` (`IDCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Car_has_Part_Part1`
    FOREIGN KEY (`IDPart`)
    REFERENCES `mydb`.`Part` (`IDPart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
